name: PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Change permission of all Scripts
        shell: bash
        run: |
          chmod -R 777 ./
      - name: Check banned word
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
        run: |
<<<<<<< HEAD
          echo $PR_NUMBER
=======
>>>>>>> main
          ./create-comment-pr.sh $PR_NUMBER